# Generated by Django 4.2.29 on 2026-03-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sacuvano',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kolekcija', models.CharField(blank=True, db_column='Kolekcija', max_length=18, null=True)),
            ],
            options={
                'db_table': 'sacuvano',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('idkat', models.AutoField(db_column='IdKat', primary_key=True, serialize=False)),
                ('naziv', models.CharField(blank=True, db_column='Naziv', max_length=20, null=True)),
                ('tip', models.CharField(blank=True, db_column='Tip', max_length=20, null=True)),
            ],
            options={
                'db_table': 'kategorija',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Skripta',
            fields=[
                ('idskr', models.AutoField(db_column='IdSkr', primary_key=True, serialize=False)),
                ('naziv', models.CharField(db_column='Naziv', max_length=20)),
                ('opis', models.CharField(blank=True, db_column='Opis', max_length=20, null=True)),
                ('fajl', models.TextField(db_column='Fajl')),
                ('odobrena', models.IntegerField(db_column='Odobrena')),
                ('idkat', models.ForeignKey(db_column='IdKat', on_delete=django.db.models.deletion.DO_NOTHING, to='materials.kategorija')),
                ('idkor', models.ForeignKey(blank=True, db_column='IdKor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.korisnik')),
            ],
            options={
                'db_table': 'skripta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ocena', models.IntegerField(blank=True, db_column='Ocena', null=True)),
                ('idkor', models.ForeignKey(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.korisnik')),
                ('idskr', models.ForeignKey(db_column='IdSkr', on_delete=django.db.models.deletion.DO_NOTHING, to='materials.skripta')),
            ],
            options={
                'db_table': 'ocena',
                'managed': True,
                'unique_together': {('idkor', 'idskr')},
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tekst', models.CharField(blank=True, db_column='Tekst', max_length=512, null=True)),
                ('idkor', models.ForeignKey(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.korisnik')),
                ('idskr', models.ForeignKey(db_column='IdSkr', on_delete=django.db.models.deletion.DO_NOTHING, to='materials.skripta')),
            ],
            options={
                'db_table': 'komentar',
                'managed': True,
                'unique_together': {('idkor', 'idskr')},
            },
        ),
        migrations.CreateModel(
            name='KategorijaNad',
            fields=[
                ('idkatnad', models.ForeignKey(db_column='IdKatNad', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='materials.kategorija')),
                ('idkatpod', models.ForeignKey(db_column='IdKatPod', on_delete=django.db.models.deletion.DO_NOTHING, related_name='kategorijanad_idkatpod_set', to='materials.kategorija')),
            ],
            options={
                'db_table': 'kategorija_nad',
                'managed': True,
                'unique_together': {('idkatnad', 'idkatpod')},
            },
        ),
    ]
