# Generated by Django 4.2.29 on 2026-03-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skripta',
            name='fajl',
            field=models.FileField(db_column='Fajl', upload_to=''),
        ),
    ]
