# Generated by Django 4.2.29 on 2026-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_skripta_fajl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skripta',
            name='fajl',
            field=models.FileField(db_column='Fajl', upload_to='skripte/'),
        ),
        migrations.AlterField(
            model_name='skripta',
            name='odobrena',
            field=models.IntegerField(db_column='Odobrena', default=0),
        ),
    ]
