# Generated by Django 4.2.29 on 2026-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_skripta_fajl_alter_skripta_odobrena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skripta',
            name='naziv',
            field=models.CharField(db_column='Naziv', max_length=50),
        ),
        migrations.AlterField(
            model_name='skripta',
            name='opis',
            field=models.CharField(blank=True, db_column='Opis', max_length=255, null=True),
        ),
    ]
