# Generated by Django 4.2.29 on 2026-03-14 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_korisnik_email'),
        ('materials', '0004_alter_skripta_naziv_alter_skripta_opis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komentar',
            name='id',
        ),
        migrations.AlterField(
            model_name='komentar',
            name='idkor',
            field=models.ForeignKey(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.korisnik'),
        ),
    ]
