# Generated by Django 4.2.29 on 2026-03-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_korisnik_idrol_alter_korisnik_lozinka'),
        ('materials', '0005_remove_komentar_id_alter_komentar_idkor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocena',
            name='id',
        ),
        migrations.AlterField(
            model_name='ocena',
            name='idkor',
            field=models.ForeignKey(db_column='IdKor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.korisnik'),
        ),
    ]
