# Generated by Django 4.2.29 on 2026-03-15 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_korisnik_idrol_alter_korisnik_lozinka'),
        ('materials', '0006_remove_ocena_id_alter_ocena_idkor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='idkor',
            field=models.ForeignKey(db_column='IdKor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.korisnik'),
        ),
        migrations.AlterField(
            model_name='komentar',
            name='idskr',
            field=models.ForeignKey(db_column='IdSkr', on_delete=django.db.models.deletion.CASCADE, to='materials.skripta'),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='idkor',
            field=models.ForeignKey(db_column='IdKor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.korisnik'),
        ),
        migrations.AlterField(
            model_name='ocena',
            name='idskr',
            field=models.ForeignKey(db_column='IdSkr', on_delete=django.db.models.deletion.CASCADE, to='materials.skripta'),
        ),
    ]
