# Generated by Django 6.0.3 on 2026-03-15 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_remove_ocena_id_alter_ocena_idkor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sacuvano',
            options={'managed': True},
        ),
    ]
