# Generated by Django 6.0.3 on 2026-03-15 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_komentar_idkor_alter_komentar_idskr_and_more'),
        ('materials', '0007_alter_sacuvano_options'),
    ]

    operations = [
    ]
