# Generated by Django 4.2.29 on 2026-03-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('idrol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('opis', models.CharField(db_column='Opis', max_length=20)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('idkor', models.AutoField(db_column='IdKor', primary_key=True, serialize=False)),
                ('kor_ime', models.CharField(db_column='Kor_Ime', max_length=20)),
                ('lozinka', models.CharField(db_column='Lozinka', max_length=20)),
                ('email', models.CharField(db_column='Email', max_length=18)),
                ('idrol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.role')),
            ],
            options={
                'db_table': 'korisnik',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prijateljstvo',
            fields=[
                ('idkor1', models.ForeignKey(db_column='IdKor1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.korisnik')),
                ('status', models.CharField(db_column='Status', max_length=20)),
                ('idkor2', models.ForeignKey(db_column='IdKor2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prijateljstvo_idkor2_set', to='accounts.korisnik')),
            ],
            options={
                'db_table': 'prijateljstvo',
                'managed': True,
                'unique_together': {('idkor1', 'idkor2')},
            },
        ),
    ]
