# Generated by Django 4.2.29 on 2026-03-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='email',
            field=models.CharField(db_column='Email', max_length=100),
        ),
    ]
