# Generated by Django 4.2.29 on 2026-03-15 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_korisnik_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='idrol',
            field=models.ForeignKey(db_column='IdRol', default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.role'),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='lozinka',
            field=models.CharField(db_column='Lozinka', max_length=500),
        ),
    ]
